import click
from flask_migrate import (
    Migrate,
)
from flask_migrate import current as alembic_current
from flask_migrate import downgrade as alembic_downgrade
from flask_migrate import init as alembic_init
from flask_migrate import migrate as alembic_migrate
from flask_migrate import revision as alembic_revision
from flask_migrate import stamp as alembic_stamp
from flask_migrate import upgrade as alembic_upgrade

from ..core.app import create_app
from ..core.extensions import db

app = create_app()

# Initialize Flask-Migrate
migrate = Migrate(app, db)


# Provide 'flask db' CLI group compatible with our dependency versions
@app.cli.group()
def db():
    """Perform database migrations."""
    pass


@db.command("init")
def db_init():
    """Initialize a new migrations repository."""
    alembic_init()


@db.command("migrate")
@click.option("-m", "--message", default=None, help="Message for the migration")
def db_migrate(message):
    """Autogenerate a new migration."""
    alembic_migrate(message=message)


@db.command("upgrade")
@click.argument("revision", default="head", required=False)
def db_upgrade(revision):
    """Upgrade to a later migration."""
    alembic_upgrade(revision=revision or "head")


@db.command("downgrade")
@click.argument("revision", default="-1", required=False)
def db_downgrade(revision):
    """Revert to a previous migration."""
    alembic_downgrade(revision=revision or "-1")


@db.command("stamp")
@click.argument("revision", default="head", required=False)
def db_stamp(revision):
    """Stamp the revision table with the given revision; don't run any migrations."""
    alembic_stamp(revision=revision or "head")


@db.command("revision")
@click.option("-m", "--message", default=None, help="Message for the revision")
@click.option(
    "--autogenerate",
    is_flag=True,
    default=False,
    help="Populate revision with autogenerated operations",
)
def db_revision(message, autogenerate):
    """Create a new revision file."""
    alembic_revision(message=message, autogenerate=autogenerate)


@db.command("current")
def db_current():
    """Display the current revision for each database."""
    alembic_current()


if __name__ == "__main__":
    app.run()
