import type { Config } from "tailwindcss"

const config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Основные цвета системы
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // Дополнительные цвета для поверхностей
        surface: {
          DEFAULT: "hsl(var(--surface))",
          foreground: "hsl(var(--surface-foreground))",
        },
        // Цвета для кода
        code: {
          DEFAULT: "hsl(var(--code))",
          foreground: "hsl(var(--code-foreground))",
          highlight: "hsl(var(--code-highlight))",
          number: "hsl(var(--code-number))",
        },
        // Цвета для выделения
        selection: {
          DEFAULT: "hsl(var(--selection))",
          foreground: "hsl(var(--selection-foreground))",
        },
        // Цвета для графиков
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        // Расширенная палитра цветов
        blue: {
          50: "hsl(var(--color-blue-50))",
          100: "hsl(var(--color-blue-100))",
          200: "hsl(var(--color-blue-200))",
          300: "hsl(var(--color-blue-300))",
          400: "hsl(var(--color-blue-400))",
          500: "hsl(var(--color-blue-500))",
          600: "hsl(var(--color-blue-600))",
          700: "hsl(var(--color-blue-700))",
          800: "hsl(var(--color-blue-800))",
          900: "hsl(var(--color-blue-900))",
        },
        green: {
          50: "hsl(var(--color-green-50))",
          100: "hsl(var(--color-green-100))",
          200: "hsl(var(--color-green-200))",
          300: "hsl(var(--color-green-300))",
          400: "hsl(var(--color-green-400))",
          500: "hsl(var(--color-green-500))",
          600: "hsl(var(--color-green-600))",
          700: "hsl(var(--color-green-700))",
          800: "hsl(var(--color-green-800))",
          900: "hsl(var(--color-green-900))",
        },
        red: {
          50: "hsl(var(--color-red-50))",
          100: "hsl(var(--color-red-100))",
          200: "hsl(var(--color-red-200))",
          300: "hsl(var(--color-red-300))",
          400: "hsl(var(--color-red-400))",
          500: "hsl(var(--color-red-500))",
          600: "hsl(var(--color-red-600))",
          700: "hsl(var(--color-red-700))",
          800: "hsl(var(--color-red-800))",
          900: "hsl(var(--color-red-900))",
        },
        orange: {
          50: "hsl(var(--color-orange-50))",
          100: "hsl(var(--color-orange-100))",
          200: "hsl(var(--color-orange-200))",
          300: "hsl(var(--color-orange-300))",
          400: "hsl(var(--color-orange-400))",
          500: "hsl(var(--color-orange-500))",
          600: "hsl(var(--color-orange-600))",
          700: "hsl(var(--color-orange-700))",
          800: "hsl(var(--color-orange-800))",
          900: "hsl(var(--color-orange-900))",
        },
        purple: {
          50: "hsl(var(--color-purple-50))",
          100: "hsl(var(--color-purple-100))",
          200: "hsl(var(--color-purple-200))",
          300: "hsl(var(--color-purple-300))",
          400: "hsl(var(--color-purple-400))",
          500: "hsl(var(--color-purple-500))",
          600: "hsl(var(--color-purple-600))",
          700: "hsl(var(--color-purple-700))",
          800: "hsl(var(--color-purple-800))",
          900: "hsl(var(--color-purple-900))",
        },
        teal: {
          50: "hsl(var(--color-teal-50))",
          100: "hsl(var(--color-teal-100))",
          200: "hsl(var(--color-teal-200))",
          300: "hsl(var(--color-teal-300))",
          400: "hsl(var(--color-teal-400))",
          500: "hsl(var(--color-teal-500))",
          600: "hsl(var(--color-teal-600))",
          700: "hsl(var(--color-teal-700))",
          800: "hsl(var(--color-teal-800))",
          900: "hsl(var(--color-teal-900))",
        },
        amber: {
          50: "hsl(var(--color-amber-50))",
          100: "hsl(var(--color-amber-100))",
          200: "hsl(var(--color-amber-200))",
          300: "hsl(var(--color-amber-300))",
          400: "hsl(var(--color-amber-400))",
          500: "hsl(var(--color-amber-500))",
          600: "hsl(var(--color-amber-600))",
          700: "hsl(var(--color-amber-700))",
          800: "hsl(var(--color-amber-800))",
          900: "hsl(var(--color-amber-900))",
        },
        lime: {
          50: "hsl(var(--color-lime-50))",
          100: "hsl(var(--color-lime-100))",
          200: "hsl(var(--color-lime-200))",
          300: "hsl(var(--color-lime-300))",
          400: "hsl(var(--color-lime-400))",
          500: "hsl(var(--color-lime-500))",
          600: "hsl(var(--color-lime-600))",
          700: "hsl(var(--color-lime-700))",
          800: "hsl(var(--color-lime-800))",
          900: "hsl(var(--color-lime-900))",
        },
        rose: {
          50: "hsl(var(--color-rose-50))",
          100: "hsl(var(--color-rose-100))",
          200: "hsl(var(--color-rose-200))",
          300: "hsl(var(--color-rose-300))",
          400: "hsl(var(--color-rose-400))",
          500: "hsl(var(--color-rose-500))",
          600: "hsl(var(--color-rose-600))",
          700: "hsl(var(--color-rose-700))",
          800: "hsl(var(--color-rose-800))",
          900: "hsl(var(--color-rose-900))",
        },
        stone: {
          50: "hsl(var(--color-stone-50))",
          100: "hsl(var(--color-stone-100))",
          200: "hsl(var(--color-stone-200))",
          300: "hsl(var(--color-stone-300))",
          400: "hsl(var(--color-stone-400))",
          500: "hsl(var(--color-stone-500))",
          600: "hsl(var(--color-stone-600))",
          700: "hsl(var(--color-stone-700))",
          800: "hsl(var(--color-stone-800))",
          900: "hsl(var(--color-stone-900))",
        },
        zinc: {
          50: "hsl(var(--color-zinc-50))",
          100: "hsl(var(--color-zinc-100))",
          200: "hsl(var(--color-zinc-200))",
          300: "hsl(var(--color-zinc-300))",
          400: "hsl(var(--color-zinc-400))",
          500: "hsl(var(--color-zinc-500))",
          600: "hsl(var(--color-zinc-600))",
          700: "hsl(var(--color-zinc-700))",
          800: "hsl(var(--color-zinc-800))",
          900: "hsl(var(--color-zinc-900))",
        },
        gray: {
          50: "hsl(var(--color-gray-50))",
          100: "hsl(var(--color-gray-100))",
          200: "hsl(var(--color-gray-200))",
          300: "hsl(var(--color-gray-300))",
          400: "hsl(var(--color-gray-400))",
          500: "hsl(var(--color-gray-500))",
          600: "hsl(var(--color-gray-600))",
          700: "hsl(var(--color-gray-700))",
          800: "hsl(var(--color-gray-800))",
          900: "hsl(var(--color-gray-900))",
        },
        slate: {
          50: "hsl(var(--color-slate-50))",
          100: "hsl(var(--color-slate-100))",
          200: "hsl(var(--color-slate-200))",
          300: "hsl(var(--color-slate-300))",
          400: "hsl(var(--color-slate-400))",
          500: "hsl(var(--color-slate-500))",
          600: "hsl(var(--color-slate-600))",
          700: "hsl(var(--color-slate-700))",
          800: "hsl(var(--color-slate-800))",
          900: "hsl(var(--color-slate-900))",
        },
      },
      borderRadius: {
        sm: "calc(var(--radius) - 4px)",
        md: "calc(var(--radius) - 2px)",
        lg: "var(--radius)",
        xl: "calc(var(--radius) + 4px)",
      },
      fontFamily: {
        sans: "var(--font-sans)",
        mono: "var(--font-mono)",
      },
      screens: {
        "3xl": "1600px",
        "4xl": "2000px",
      },
    },
  },
} satisfies Config

export default config 