#!/bin/bash
# Проверка доступности сервера извне

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "=========================================="
echo "Проверка доступности сервера извне"
echo "=========================================="
echo ""

cd "$PROJECT_ROOT"

SERVER_IP="38.242.149.188"
DOMAIN="ovrin.xyz"

echo "1. Проверка доступности портов извне:"
echo "---"
echo "Проверьте через онлайн-сервисы:"
echo "  https://www.yougetsignal.com/tools/open-ports/"
echo "  https://www.canyouseeme.org/"
echo ""
echo "Или с другого сервера:"
echo "  telnet $SERVER_IP 80"
echo "  telnet $SERVER_IP 443"
echo ""
echo "Или через nmap:"
echo "  nmap -p 80,443 $SERVER_IP"
echo ""

echo "2. Проверка файрвола провайдера:"
echo "---"
echo "Если используете:"
echo "  - Contabo: Проверьте панель управления > Firewall"
echo "  - DigitalOcean: Проверьте Networking > Firewalls"
echo "  - AWS: Проверьте Security Groups"
echo "  - Hetzner: Проверьте Firewall в консоли"
echo ""
echo "Убедитесь, что разрешены входящие соединения на:"
echo "  - TCP порт 80 (HTTP)"
echo "  - TCP порт 443 (HTTPS)"
echo ""

echo "3. Проверка iptables на сервере:"
echo "---"
if command -v iptables > /dev/null 2>&1; then
    echo "Правила iptables для портов 80 и 443:"
    iptables -L INPUT -n -v | grep -E "80|443" || echo "  Нет правил для портов 80/443"
    echo ""
    echo "Если порты заблокированы, добавьте правила:"
    echo "  iptables -A INPUT -p tcp --dport 80 -j ACCEPT"
    echo "  iptables -A INPUT -p tcp --dport 443 -j ACCEPT"
    echo "  iptables-save > /etc/iptables/rules.v4  # Сохранить правила"
else
    echo "iptables не установлен"
fi
echo ""

echo "4. Проверка Docker портов:"
echo "---"
echo "Убедитесь, что порты проброшены в docker-compose.yml:"
grep -A 2 "ports:" docker-compose.yml | grep -E "80|443" || echo "  Порты не найдены в docker-compose.yml"
echo ""

echo "5. Тест подключения извне:"
echo "---"
echo "Попробуйте с вашего компьютера:"
echo ""
echo "  # HTTP"
echo "  curl -v http://$DOMAIN"
echo "  curl -v http://$SERVER_IP"
echo ""
echo "  # HTTPS"
echo "  curl -v -k https://$DOMAIN"
echo "  curl -v -k https://$SERVER_IP"
echo ""
echo "  # Или через браузер:"
echo "  http://$DOMAIN"
echo "  https://$DOMAIN"
echo ""

echo "6. Проверка в реальном времени (мониторинг логов):"
echo "---"
echo "Откройте второй терминал и запустите:"
echo "  docker-compose logs -f nginx"
echo ""
echo "Затем попробуйте подключиться извне - в логах должны появиться новые записи"
echo ""

echo "7. Проверка через внешний сервис:"
echo "---"
echo "Используйте онлайн-сервисы для проверки:"
echo "  - https://downforeveryoneorjustme.com/ovrin.xyz"
echo "  - https://www.isitdownrightnow.com/ovrin.xyz.html"
echo "  - https://www.uptrends.com/tools/uptime"
echo ""

echo "=========================================="
echo "Возможные проблемы и решения:"
echo "=========================================="
echo ""
echo "1. ФАЙРВОЛ ПРОВАЙДЕРА:"
echo "   ⚠️  Самый частый случай!"
echo "   Решение: Откройте панель управления хостингом и разрешите порты 80/443"
echo ""
echo "2. iptables блокирует:"
echo "   Решение: Добавьте правила (см. выше)"
echo ""
echo "3. Docker не пробросил порты:"
echo "   Решение: Перезапустите контейнеры: docker-compose restart nginx"
echo ""
echo "4. DNS ещё не распространился:"
echo "   Решение: Подождите 5-15 минут, проверьте через другой DNS:"
echo "     nslookup ovrin.xyz 8.8.8.8"
echo ""
echo "5. Провайдер блокирует порты по умолчанию:"
echo "   Решение: Обратитесь в поддержку хостинга"
echo ""
echo "=========================================="

