"""Add performance indexes

Revision ID: add_perf_indexes_001
Revises: cafc38e2b822
Create Date: 2025-01-XX XX:XX:XX.XXXXXX

"""
from alembic import op
import sqlalchemy as sa

revision = 'add_perf_indexes_001'
down_revision = 'cafc38e2b822'
branch_labels = None
depends_on = None

def upgrade():

    op.create_index('idx_user_project_id', 'user', ['project_id'], unique=False)
    op.create_index('idx_user_activity_project_id', 'user_activity', ['project_id'], unique=False)
    op.create_index('idx_user_activity_created_at', 'user_activity', ['created_at'], unique=False)
    op.create_index('idx_user_activity_user_id', 'user_activity', ['user_id'], unique=False)
    op.create_index('idx_user_action_log_project_id', 'user_action_log', ['project_id'], unique=False)
    op.create_index('idx_user_action_log_user_id', 'user_action_log', ['user_id'], unique=False)
    op.create_index('idx_user_action_log_created_at', 'user_action_log', ['created_at'], unique=False)

    op.create_index('idx_project_user_role_project_id', 'project_user_role', ['project_id'], unique=False)
    op.create_index('idx_project_user_role_user_id', 'project_user_role', ['user_id'], unique=False)
    op.create_index('idx_project_invite_code_project_id', 'project_invite_code', ['project_id'], unique=False)
    op.create_index('idx_project_invite_code_is_used', 'project_invite_code', ['is_used'], unique=False)
    op.create_index('idx_project_invite_code_expires_at', 'project_invite_code', ['expires_at'], unique=False)

    op.create_index('idx_game_project_id', 'game', ['project_id'], unique=False)
    op.create_index('idx_game_status', 'game', ['status'], unique=False)
    op.create_index('idx_game_is_active', 'game', ['is_active'], unique=False)
    op.create_index('idx_game_chat_settings_project_id', 'game_chat_settings', ['project_id'], unique=False)
    op.create_index('idx_game_status_project_id', 'game_status', ['project_id'], unique=False)
    op.create_index('idx_game_configuration_project_id', 'game_configuration', ['project_id'], unique=False)
    op.create_index('idx_game_invite_code_project_id', 'game_invite_code', ['project_id'], unique=False)
    op.create_index('idx_game_invite_code_game_id', 'game_invite_code', ['game_id'], unique=False)
    op.create_index('idx_game_security_log_project_id', 'game_security_log', ['project_id'], unique=False)
    op.create_index('idx_game_security_log_game_id', 'game_security_log', ['game_id'], unique=False)
    op.create_index('idx_game_security_log_created_at', 'game_security_log', ['created_at'], unique=False)
    op.create_index('idx_game_key_price_project_id', 'game_key_price', ['project_id'], unique=False)
    op.create_index('idx_changelog_entry_project_id', 'changelog_entry', ['project_id'], unique=False)
    op.create_index('idx_changelog_entry_game_id', 'changelog_entry', ['game_id'], unique=False)
    op.create_index('idx_announcement_project_id', 'announcement', ['project_id'], unique=False)
    op.create_index('idx_announcement_game_id', 'announcement', ['game_id'], unique=False)
    op.create_index('idx_file_meta_project_id', 'file_meta', ['project_id'], unique=False)
    op.create_index('idx_file_meta_game_id', 'file_meta', ['game_id'], unique=False)

    op.create_index('idx_key_project_id', 'key', ['project_id'], unique=False)
    op.create_index('idx_key_user_id', 'key', ['user_id'], unique=False)
    op.create_index('idx_key_game_id', 'key', ['game_id'], unique=False)
    op.create_index('idx_key_status', 'key', ['status'], unique=False)
    op.create_index('idx_key_expires_at', 'key', ['expires_at'], unique=False)
    op.create_index('idx_key_created_at', 'key', ['created_at'], unique=False)
    op.create_index('idx_key_analytics_key_id', 'key_analytics', ['key_id'], unique=False)
    op.create_index('idx_key_analytics_date', 'key_analytics', ['date'], unique=False)

    op.create_index('idx_token_transaction_project_id', 'token_transaction', ['project_id'], unique=False)
    op.create_index('idx_token_transaction_user_id', 'token_transaction', ['user_id'], unique=False)
    op.create_index('idx_token_transaction_created_at', 'token_transaction', ['created_at'], unique=False)
    op.create_index('idx_referral_code_project_id', 'referral_code', ['project_id'], unique=False)
    op.create_index('idx_referral_code_used', 'referral_code', ['used'], unique=False)
    op.create_index('idx_referral_code_expires_at', 'referral_code', ['expires_at'], unique=False)

    op.create_index('idx_user_game_permission_project_id', 'user_game_permission', ['project_id'], unique=False)
    op.create_index('idx_user_game_permission_user_id', 'user_game_permission', ['user_id'], unique=False)
    op.create_index('idx_user_game_permission_game_id', 'user_game_permission', ['game_id'], unique=False)
    op.create_index('idx_developer_game_permission_project_id', 'developer_game_permission', ['project_id'], unique=False)
    op.create_index('idx_developer_game_permission_user_id', 'developer_game_permission', ['user_id'], unique=False)

    op.create_index('idx_role_project_id', 'role', ['project_id'], unique=False)
    op.create_index('idx_permission_project_id', 'permission', ['project_id'], unique=False)
    op.create_index('idx_user_role_user_id', 'user_role', ['user_id'], unique=False)
    op.create_index('idx_user_role_role_id', 'user_role', ['role_id'], unique=False)
    op.create_index('idx_role_permission_role_id', 'role_permission', ['role_id'], unique=False)
    op.create_index('idx_role_permission_permission_id', 'role_permission', ['permission_id'], unique=False)
    op.create_index('idx_attribute_rule_project_id', 'attribute_rule', ['project_id'], unique=False)
    op.create_index('idx_attribute_rule_is_active', 'attribute_rule', ['is_active'], unique=False)
    op.create_index('idx_resource_attribute_project_id', 'resource_attribute', ['project_id'], unique=False)
    op.create_index('idx_resource_attribute_resource', 'resource_attribute', ['resource_type', 'resource_id'], unique=False)

    op.create_index('idx_chat_message_project_id', 'chat_message', ['project_id'], unique=False)
    op.create_index('idx_chat_message_created_at', 'chat_message', ['created_at'], unique=False)
    op.create_index('idx_chat_message_game_id', 'chat_message', ['game_id'], unique=False)
    op.create_index('idx_chat_group_project_id', 'chat_group', ['project_id'], unique=False)
    op.create_index('idx_chat_group_game_project_id', 'chat_group_game', ['project_id'], unique=False)
    op.create_index('idx_telegram_bot_project_id', 'telegram_bot', ['project_id'], unique=False)
    op.create_index('idx_discord_webhook_project_id', 'discord_webhook', ['project_id'], unique=False)

    op.create_index('idx_notification_project_id', 'notification', ['project_id'], unique=False)
    op.create_index('idx_notification_user_id', 'notification', ['user_id'], unique=False)
    op.create_index('idx_notification_is_read', 'notification', ['is_read'], unique=False)
    op.create_index('idx_notification_created_at', 'notification', ['created_at'], unique=False)
    op.create_index('idx_notification_is_scheduled', 'notification', ['is_scheduled'], unique=False)

    op.create_index('idx_webhook_project_id', 'webhook', ['project_id'], unique=False)
    op.create_index('idx_webhook_is_active', 'webhook', ['is_active'], unique=False)
    op.create_index('idx_webhook_log_webhook_id', 'webhook_log', ['webhook_id'], unique=False)
    op.create_index('idx_webhook_log_created_at', 'webhook_log', ['created_at'], unique=False)

    op.create_index('idx_server_project_id', 'server', ['project_id'], unique=False)
    op.create_index('idx_server_is_active', 'server', ['is_active'], unique=False)
    op.create_index('idx_billing_project_id', 'billing', ['project_id'], unique=False)
    op.create_index('idx_project_api_key_project_id', 'project_api_key', ['project_id'], unique=False)

    op.create_index('idx_login_attempt_project_id', 'login_attempt', ['project_id'], unique=False)
    op.create_index('idx_login_attempt_ip_address', 'login_attempt', ['ip_address'], unique=False)
    op.create_index('idx_login_attempt_created_at', 'login_attempt', ['created_at'], unique=False)
    op.create_index('idx_blockedip_project_id', 'blockedip', ['project_id'], unique=False)
    op.create_index('idx_blockedip_ip_address', 'blockedip', ['ip_address'], unique=False)
    op.create_index('idx_blockedip_is_active', 'blockedip', ['is_active'], unique=False)
    op.create_index('idx_blockedhwid_project_id', 'blockedhwid', ['project_id'], unique=False)
    op.create_index('idx_blockedhwid_is_active', 'blockedhwid', ['is_active'], unique=False)
    op.create_index('idx_blocked_fingerprint_project_id', 'blocked_fingerprint', ['project_id'], unique=False)
    op.create_index('idx_blocked_fingerprint_is_active', 'blocked_fingerprint', ['is_active'], unique=False)
    op.create_index('idx_security_event_project_id', 'security_event', ['project_id'], unique=False)
    op.create_index('idx_security_event_created_at', 'security_event', ['created_at'], unique=False)
    op.create_index('idx_security_analytics_project_id', 'security_analytics', ['project_id'], unique=False)
    op.create_index('idx_security_analytics_date', 'security_analytics', ['date'], unique=False)
    op.create_index('idx_security_rule_project_id', 'security_rule', ['project_id'], unique=False)
    op.create_index('idx_security_rule_is_active', 'security_rule', ['is_active'], unique=False)

    op.create_index('idx_two_factor_auth_project_id', 'two_factor_auth', ['project_id'], unique=False)
    op.create_index('idx_two_factor_backup_code_project_id', 'two_factor_backup_code', ['project_id'], unique=False)
    op.create_index('idx_two_factor_backup_code_user_id', 'two_factor_backup_code', ['user_id'], unique=False)
    op.create_index('idx_two_factor_backup_code_is_used', 'two_factor_backup_code', ['is_used'], unique=False)
    op.create_index('idx_two_factor_session_project_id', 'two_factor_session', ['project_id'], unique=False)
    op.create_index('idx_two_factor_session_user_id', 'two_factor_session', ['user_id'], unique=False)
    op.create_index('idx_two_factor_session_expires_at', 'two_factor_session', ['expires_at'], unique=False)

    op.create_index('idx_loader_project_id', 'loader', ['project_id'], unique=False)
    op.create_index('idx_loader_changelog_project_id', 'loader_changelog', ['project_id'], unique=False)
    op.create_index('idx_loader_configuration_project_id', 'loader_configuration', ['project_id'], unique=False)
    op.create_index('idx_loader_download_log_project_id', 'loader_download_log', ['project_id'], unique=False)
    op.create_index('idx_loader_game_assignment_project_id', 'loader_game_assignment', ['project_id'], unique=False)
    op.create_index('idx_loader_notification_project_id', 'loader_notification', ['project_id'], unique=False)

    op.create_index('idx_remote_category_project_id', 'remote_category', ['project_id'], unique=False)
    op.create_index('idx_remote_feature_project_id', 'remote_feature', ['project_id'], unique=False)
    op.create_index('idx_remote_feature_log_project_id', 'remote_feature_log', ['project_id'], unique=False)
    op.create_index('idx_remote_feature_log_feature_id', 'remote_feature_log', ['feature_id'], unique=False)

    op.create_index('idx_message_project_id', 'message', ['project_id'], unique=False)
    op.create_index('idx_message_created_at', 'message', ['created_at'], unique=False)
    op.create_index('idx_file_download_log_project_id', 'file_download_log', ['project_id'], unique=False)
    op.create_index('idx_file_download_log_timestamp', 'file_download_log', ['timestamp'], unique=False)

    op.create_index('idx_user_activity_project_created', 'user_activity', ['project_id', 'created_at'], unique=False)
    op.create_index('idx_key_project_status', 'key', ['project_id', 'status'], unique=False)
    op.create_index('idx_key_project_created', 'key', ['project_id', 'created_at'], unique=False)
    op.create_index('idx_notification_project_user_read', 'notification', ['project_id', 'user_id', 'is_read'], unique=False)
    op.create_index('idx_chat_message_project_created', 'chat_message', ['project_id', 'created_at'], unique=False)
    op.create_index('idx_game_project_active', 'game', ['project_id', 'is_active'], unique=False)

def downgrade():

    op.drop_index('idx_game_project_active', table_name='game')
    op.drop_index('idx_chat_message_project_created', table_name='chat_message')
    op.drop_index('idx_notification_project_user_read', table_name='notification')
    op.drop_index('idx_key_project_created', table_name='key')
    op.drop_index('idx_key_project_status', table_name='key')
    op.drop_index('idx_user_activity_project_created', table_name='user_activity')

    op.drop_index('idx_file_download_log_timestamp', table_name='file_download_log')
    op.drop_index('idx_file_download_log_project_id', table_name='file_download_log')
    op.drop_index('idx_message_created_at', table_name='message')
    op.drop_index('idx_message_project_id', table_name='message')

    op.drop_index('idx_remote_feature_log_feature_id', table_name='remote_feature_log')
    op.drop_index('idx_remote_feature_log_project_id', table_name='remote_feature_log')
    op.drop_index('idx_remote_feature_project_id', table_name='remote_feature')
    op.drop_index('idx_remote_category_project_id', table_name='remote_category')

    op.drop_index('idx_loader_notification_project_id', table_name='loader_notification')
    op.drop_index('idx_loader_game_assignment_project_id', table_name='loader_game_assignment')
    op.drop_index('idx_loader_download_log_project_id', table_name='loader_download_log')
    op.drop_index('idx_loader_configuration_project_id', table_name='loader_configuration')
    op.drop_index('idx_loader_changelog_project_id', table_name='loader_changelog')
    op.drop_index('idx_loader_project_id', table_name='loader')

    op.drop_index('idx_two_factor_session_expires_at', table_name='two_factor_session')
    op.drop_index('idx_two_factor_session_user_id', table_name='two_factor_session')
    op.drop_index('idx_two_factor_session_project_id', table_name='two_factor_session')
    op.drop_index('idx_two_factor_backup_code_is_used', table_name='two_factor_backup_code')
    op.drop_index('idx_two_factor_backup_code_user_id', table_name='two_factor_backup_code')
    op.drop_index('idx_two_factor_backup_code_project_id', table_name='two_factor_backup_code')
    op.drop_index('idx_two_factor_auth_project_id', table_name='two_factor_auth')

    op.drop_index('idx_security_rule_is_active', table_name='security_rule')
    op.drop_index('idx_security_rule_project_id', table_name='security_rule')
    op.drop_index('idx_security_analytics_date', table_name='security_analytics')
    op.drop_index('idx_security_analytics_project_id', table_name='security_analytics')
    op.drop_index('idx_security_event_created_at', table_name='security_event')
    op.drop_index('idx_security_event_project_id', table_name='security_event')
    op.drop_index('idx_blocked_fingerprint_is_active', table_name='blocked_fingerprint')
    op.drop_index('idx_blocked_fingerprint_project_id', table_name='blocked_fingerprint')
    op.drop_index('idx_blockedhwid_is_active', table_name='blockedhwid')
    op.drop_index('idx_blockedhwid_project_id', table_name='blockedhwid')
    op.drop_index('idx_blockedip_is_active', table_name='blockedip')
    op.drop_index('idx_blockedip_ip_address', table_name='blockedip')
    op.drop_index('idx_blockedip_project_id', table_name='blockedip')
    op.drop_index('idx_login_attempt_created_at', table_name='login_attempt')
    op.drop_index('idx_login_attempt_ip_address', table_name='login_attempt')
    op.drop_index('idx_login_attempt_project_id', table_name='login_attempt')

    op.drop_index('idx_project_api_key_project_id', table_name='project_api_key')
    op.drop_index('idx_billing_project_id', table_name='billing')
    op.drop_index('idx_server_is_active', table_name='server')
    op.drop_index('idx_server_project_id', table_name='server')

    op.drop_index('idx_webhook_log_created_at', table_name='webhook_log')
    op.drop_index('idx_webhook_log_webhook_id', table_name='webhook_log')
    op.drop_index('idx_webhook_is_active', table_name='webhook')
    op.drop_index('idx_webhook_project_id', table_name='webhook')

    op.drop_index('idx_notification_is_scheduled', table_name='notification')
    op.drop_index('idx_notification_created_at', table_name='notification')
    op.drop_index('idx_notification_is_read', table_name='notification')
    op.drop_index('idx_notification_user_id', table_name='notification')
    op.drop_index('idx_notification_project_id', table_name='notification')

    op.drop_index('idx_discord_webhook_project_id', table_name='discord_webhook')
    op.drop_index('idx_telegram_bot_project_id', table_name='telegram_bot')
    op.drop_index('idx_chat_group_game_project_id', table_name='chat_group_game')
    op.drop_index('idx_chat_group_project_id', table_name='chat_group')
    op.drop_index('idx_chat_message_game_id', table_name='chat_message')
    op.drop_index('idx_chat_message_created_at', table_name='chat_message')
    op.drop_index('idx_chat_message_project_id', table_name='chat_message')

    op.drop_index('idx_resource_attribute_resource', table_name='resource_attribute')
    op.drop_index('idx_resource_attribute_project_id', table_name='resource_attribute')
    op.drop_index('idx_attribute_rule_is_active', table_name='attribute_rule')
    op.drop_index('idx_attribute_rule_project_id', table_name='attribute_rule')
    op.drop_index('idx_role_permission_permission_id', table_name='role_permission')
    op.drop_index('idx_role_permission_role_id', table_name='role_permission')
    op.drop_index('idx_user_role_role_id', table_name='user_role')
    op.drop_index('idx_user_role_user_id', table_name='user_role')
    op.drop_index('idx_permission_project_id', table_name='permission')
    op.drop_index('idx_role_project_id', table_name='role')

    op.drop_index('idx_developer_game_permission_user_id', table_name='developer_game_permission')
    op.drop_index('idx_developer_game_permission_project_id', table_name='developer_game_permission')
    op.drop_index('idx_user_game_permission_game_id', table_name='user_game_permission')
    op.drop_index('idx_user_game_permission_user_id', table_name='user_game_permission')
    op.drop_index('idx_user_game_permission_project_id', table_name='user_game_permission')

    op.drop_index('idx_referral_code_expires_at', table_name='referral_code')
    op.drop_index('idx_referral_code_used', table_name='referral_code')
    op.drop_index('idx_referral_code_project_id', table_name='referral_code')
    op.drop_index('idx_token_transaction_created_at', table_name='token_transaction')
    op.drop_index('idx_token_transaction_user_id', table_name='token_transaction')
    op.drop_index('idx_token_transaction_project_id', table_name='token_transaction')

    op.drop_index('idx_key_analytics_date', table_name='key_analytics')
    op.drop_index('idx_key_analytics_key_id', table_name='key_analytics')
    op.drop_index('idx_key_created_at', table_name='key')
    op.drop_index('idx_key_expires_at', table_name='key')
    op.drop_index('idx_key_status', table_name='key')
    op.drop_index('idx_key_game_id', table_name='key')
    op.drop_index('idx_key_user_id', table_name='key')
    op.drop_index('idx_key_project_id', table_name='key')

    op.drop_index('idx_file_meta_game_id', table_name='file_meta')
    op.drop_index('idx_file_meta_project_id', table_name='file_meta')
    op.drop_index('idx_announcement_game_id', table_name='announcement')
    op.drop_index('idx_announcement_project_id', table_name='announcement')
    op.drop_index('idx_changelog_entry_game_id', table_name='changelog_entry')
    op.drop_index('idx_changelog_entry_project_id', table_name='changelog_entry')
    op.drop_index('idx_game_key_price_project_id', table_name='game_key_price')
    op.drop_index('idx_game_security_log_created_at', table_name='game_security_log')
    op.drop_index('idx_game_security_log_game_id', table_name='game_security_log')
    op.drop_index('idx_game_security_log_project_id', table_name='game_security_log')
    op.drop_index('idx_game_invite_code_game_id', table_name='game_invite_code')
    op.drop_index('idx_game_invite_code_project_id', table_name='game_invite_code')
    op.drop_index('idx_game_configuration_project_id', table_name='game_configuration')
    op.drop_index('idx_game_status_project_id', table_name='game_status')
    op.drop_index('idx_game_chat_settings_project_id', table_name='game_chat_settings')
    op.drop_index('idx_game_is_active', table_name='game')
    op.drop_index('idx_game_status', table_name='game')
    op.drop_index('idx_game_project_id', table_name='game')

    op.drop_index('idx_project_invite_code_expires_at', table_name='project_invite_code')
    op.drop_index('idx_project_invite_code_is_used', table_name='project_invite_code')
    op.drop_index('idx_project_invite_code_project_id', table_name='project_invite_code')
    op.drop_index('idx_project_user_role_user_id', table_name='project_user_role')
    op.drop_index('idx_project_user_role_project_id', table_name='project_user_role')

    op.drop_index('idx_user_action_log_created_at', table_name='user_action_log')
    op.drop_index('idx_user_action_log_user_id', table_name='user_action_log')
    op.drop_index('idx_user_action_log_project_id', table_name='user_action_log')
    op.drop_index('idx_user_activity_user_id', table_name='user_activity')
    op.drop_index('idx_user_activity_created_at', table_name='user_activity')
    op.drop_index('idx_user_activity_project_id', table_name='user_activity')
    op.drop_index('idx_user_project_id', table_name='user')
